export const FETCH_AYATS_REQUEST = "FETCH_AYATS_REQUEST";
export const FETCH_AYATS_SUCCESS = "FETCH_AYATS_SUCCESS";
export const FETCH_AYATS_FAILURE = "FETCH_AYATS_FAILURE";
export const AYATS_SEARCH = "AYATS_SEARCH";
